server:
    logLevel: RTCSTATS_LOG_LEVEL
    appEnvironment: RTCSTATS_ENVIRONMENT
    serviceType: RTCSTATS_SERVICE_TYPE

amplitude:
    key: RTCSTATS_AMPLITUDE_KEY

firehose:
    region: RTCSTATS_FIREHOSE_AWS_REGION
    meetingStatsStream: RTCSTATS_FIREHOSE_MEETING_STREAM
    pcStatsStream: RTCSTATS_FIREHOSE_PC_STREAM
    trackStatsStream: RTCSTATS_FIREHOSE_TRACKS_STREAM
    e2ePingStream: RTCSTATS_FIREHOSE_E2E_PING_STREAM
    faceLandmarksStream: RTCSTATS_FIREHOSE_FACE_LANDMARKS_STREAM
    meetingEventStream: RTCSTATS_FIREHOSE_MEETING_EVENT_STREAM

s3:
    region: RTCSTATS_S3_AWS_REGION
    bucket: RTCSTATS_S3_BUCKET
    endpoint: RTCSTATS_S3_ENDPOINT

dynamo:
    tableName: RTCSTATS_METADATA_TABLE
    endpoint: RTCSTATS_DYNAMODB_ENDPOINT

webhooks:
    apiEndpoint: RTCSTATS_WEBHOOK_ENDPOINT
    jwtAudience: RTCSTATS_JWT_AUDIENCE
    jwtIssuer: RTCSTATS_JWT_ISSUER

secretmanager:
    region: RTCSTATS_AWS_SECRET_REGION
    jwtSecretId: RTCSTATS_JWT_SECRET_ID

mongodb:
    uri: RTCSTATS_MONGODB_URI
    dbName: RTCSTATS_MONGODB_NAME
    collectionName: RTCSTATS_METADATA_COLLECTION
    gridfsBucketName: RTCSTATS_GRIDFS_BUCKET